angler/proprietary-blobs.txt, bullhead/proprietary-blobs.txt
This is needed to boot encrypted devices with the new branch for the
Nexus 5X and 6P.
=> add new encryption library

scripts/extract-factory-images.sh
The vendor partition size is extracted from fdisk output. However, since
the output is localized, egrep will fail on non-English systems.
Therefore, force English language for the fdisk command.
=> Force English to grep fdisk output

scripts/system-img-repair.sh
This is to allow openjdk 8 to work just like oracle java.
=> Adjust to allow use of openjdk 1.8

scripts/generate-vendor.sh
The releasetools.py scripts expect RADIO/{bootloader,radio}.img. Since
add-radio-file reuses the source file name, it needs to match what the
release scripts expect.
=> fix compatibility with AOSP releasetools.py

scripts/generate-vendor.sh
The vendor partition needs to be added to AB_OTA_PARTITIONS or OTA
updates do not include vendor and only end up updating system. The
dm-verity data for the vendor partition is updated either way, so
this usually ends up leading to a verified boot failure.
=> include vendor partition in marlin/sailfish OTAs

scripts/generate-vendor.sh
The AOSP build system already avoids optimizing apks outside of system:
https://android.googlesource.com/platform/build.git/+/edfd55ae999eb7bfc932cfa88a1a8dcd6bad1169
Relying on the AOSP build system for this will allow CopperheadOS to
enable optimization outside system without changing
android-prepare-vendor.
=> remove hard-wired vendor LOCAL_DEX_PREOPT := false

marlin/config-full/system-proprietary-blobs-api25.txt, marlin/config-naked/system-proprietary-blobs-api25.txt, sailfish/config-full/system-proprietary-blobs-api25.txt, sailfish/config-naked/system-proprietary-blobs-api25.txt
This is used by the standard /vendor/etc/audio_effects.conf and an error
is triggered since it's missing:
08-05 23:35:38.287   511   511 W EffectsFactory: loadLibrary() failed to open /system/lib/soundfx/libfmas.so
08-05 23:35:38.295   511   511 W EffectsFactory: loadEffect() could not get library fmas
08-05 23:35:38.296   511   511 W EffectsFactory: loadEffect() could not get library fmas
08-05 23:35:38.298   511   511 W BufferProvider: unable to find downmix effect
A consequence of this is that the MusicFX Equalizer feature doesn't
currently work.
=> add libfmas.so for marlin / sailfish

marlin/config-full/vendor-config-api26.txt, marlin/config-naked/vendor-config-api26.txt, sailfish/config-full/vendor-config-api26.txt, sailfish/config-naked/vendor-config-api26.txt
Google removed the vendor partition from fstab and put it in the device
tree as part of Treble, where it has verity enabled:
https://android.googlesource.com/kernel/msm.git/+/31dc3c7d67fa22330856a982b2cd1e6b97feda21
They also moved fstab from root to vendor, so this is installing it to
the old location.
Nexus devices still need this hack.
=> no longer need to override Pixel fstab

marlin/config-naked/bytecode-proprietary-api26.txt, sailfish/config-naked/bytecode-proprietary-api26.txt
CarrierSetup doesn't appear to have any use in the naked configuration
build. It depends on Verizon code that's not included and is triggered
by configuration in the GoogleCarrierConfig vendor.xml not present in
AOSP. CopperheadOS includes the stock vendor.xml as an overlay, but
leaves out the Verizon configuration since it depends on the app suite
and isn't required for basic LTE+ functionality without VoLTE / VoWiFi.
The permissions whitelist for CarrierSetup is also in the file for
Google Play Services (privapp-permissions-google.xml) rather than the
one for the Pixels (privapp-permissions-marlin.xml). If it's included,
that whitelist needs to be included too.
=> leave out CarrierSetup for Pixel naked config

scripts/generate-vendor.sh
It's currently added to the file before the headers are generated, which
clobbers this bit of code.
=> fix setting the fingerprint property

scripts/generate-vendor.sh
Nothing appears to break when this isn't present but it's set on stock
right before ro.hardware.fingerprint=fpc so it should be included here
too.
=> add missing ro.hardware.egl=adreno property

marlin/config-full/modules-force-api26.txt, marlin/config-full/system-proprietary-blobs-api26.txt, marlin/config-naked/modules-force-api26.txt, marlin/config-naked/system-proprietary-blobs-api26.txt, sailfish/config-full/modules-force-api26.txt, sailfish/config-full/system-proprietary-blobs-api26.txt, sailfish/config-naked/modules-force-api26.txt, sailfish/config-naked/system-proprietary-blobs-api26.txt
AOSP includes nanotool but only usually builds it in userdebug / eng
builds unlike stock where it's in the published user build.
=> build nanotool from source

marlin/config-full/system-proprietary-blobs-api26.txt, marlin/config-naked/system-proprietary-blobs-api26.txt, sailfish/config-full/system-proprietary-blobs-api26.txt, sailfish/config-naked/system-proprietary-blobs-api26.txt
Since com.android.ims.rcsmanager is included as a module, it already
pulls in com.android.ims.rcsmanager.xml as a dependency.
=> use rcsmanager permissions whitelist from AOSP

marlin/config-naked/bytecode-proprietary-api26.txt, sailfish/config-naked/bytecode-proprietary-api26.txt
This app appears to be a plugin for the DMService / SprintDM
infrastructure that's not being included. It doesn't appear to be
integrated anywhere and serves no useful purpose by itself. Nothing
breaks in the telephony tests with it removed.
=> remove DiagMon from Pixel naked configuration

scripts/generate-vendor.sh
Trying to use dexpreopt with Runtime Resource Overlays will break:
dex2oatd E 10-03 23:19:50 18417 18417 oat_writer.cc:403] No dex files in zip file '/vendor/overlay/Pixel/PixelThemeOverlay.apk': Entry not found
CopperheadOS plans to enable dexpreopt for vendor again in order to ban
executing dalvikcache_data_file for the base system again and this was
getting in the way.
=> set LOCAL_DEX_PREOPT := false for RROs

scripts/download-nexus-image.sh
This causes wget to not re-download a perfectly happy, successfully downloaded factory zip file if the script terminates at a later stage and needs to be re-executed.
Closes: #120
=> Implement factory zip caching/reusing

scripts/generate-vendor.sh, taimen/config.json, walleye/config.json
This avoids generating an incorrect add-radio-file call for the vendor
image, causing the stock factory image to be included and flashed by the
factory images and breaking booting. It moves the marlin vendor image
inclusion to the shared AB_OTA_PARTITIONS generation so it gets applied
for taimen / walleye too.
=> avoid treating vendor as a radio file

scripts/download-nexus-image.sh
The September build naming for marlin/sailfish (ppr2.180905.006) breaks the current download-nexus-image.sh script as it ends up getting two images instead of one (as there is also a marlin-ppr2.180905.006.a1).
curl ... "https://developers.google.com/android/nexus/images" | grep -i "<a href=.*marlin-ppr2.180905.006"
<td><a href="https://dl.google.com/dl/android/aosp/marlin-ppr2.180905.006-factory-df8ec974.zip"
<td><a href="https://dl.google.com/dl/android/aosp/marlin-ppr2.180905.006.a1-factory-a78fe264.zip"
=> Make factory download image grep more specific

blueline/config.json, crosshatch/config.json
This fixes the lack of audio during phone calls.  Credit to @shareefalis for tracking this down.
=> Add QtiTelephonyService.apk on blueline + crosshatch

blueline/config.json, crosshatch/config.json
This is already provided by AOSP for blueline/crosshatch:
BOARD_PRODUCTIMAGE_PARTITION_SIZE := 314572800
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_PRODUCT := product
Including this as a radio image has unclear consequences and appears to
be incorrect.
Closes #155
=> remove product from radio images

blueline/config.json, crosshatch/config.json
This is no longer present in the latest PQ3A.190505.002 release and this
app was not being included anyway.
=> remove com.google.android.factoryota.xml
